//go:build windows && amd64

package computer

import (
	"bufio"
	"context"
	"embed"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"syscall"
	"time"

	"golang.org/x/sys/windows"
)

const (
	computerWorkerVersion = "8.0.0"
	computerCallTimeout   = 30 * time.Second
)

// The Rust worker is a build artifact, generated by scripts/build-native.ps1
// before a Windows Go build. It is embedded so releases still contain one file.
//
//go:embed worker_windows_amd64.exe
var workerExecutable embed.FS

type workerController struct {
	ctx                context.Context
	mu                 sync.Mutex
	sequence           uint64
	cmd                *exec.Cmd
	stdin              io.WriteCloser
	stdout             *bufio.Reader
	temporaryDirectory string
	done               chan struct{}
}

type workerRequest struct {
	ID     uint64 `json:"id"`
	Method string `json:"method"`
	Params any    `json:"params,omitempty"`
}

type workerResponse struct {
	ID          uint64          `json:"id"`
	Result      json.RawMessage `json:"result,omitempty"`
	Error       string          `json:"error,omitempty"`
	ImageBase64 string          `json:"image_base64,omitempty"`
}

type workerExchange struct {
	response workerResponse
	err      error
}

func New(ctx context.Context) Controller {
	controller := &workerController{ctx: ctx}
	go func() {
		<-ctx.Done()
		_ = controller.Close()
	}()
	return controller
}

func (c *workerController) Close() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.stopLocked()
	return nil
}

func (c *workerController) Targets(ctx context.Context) (TargetsResult, error) {
	var windows []Window
	if _, err := c.call(ctx, "targets", struct{}{}, &windows); err != nil {
		return TargetsResult{}, err
	}
	return TargetsResult{Windows: windows}, nil
}

func (c *workerController) State(ctx context.Context, options StateOptions) ([]byte, State, error) {
	var state State
	response, err := c.call(ctx, "state", options, &state)
	if err != nil {
		return nil, State{}, err
	}
	image, err := base64.StdEncoding.DecodeString(response.ImageBase64)
	if err != nil {
		return nil, State{}, fmt.Errorf("decode Rust computer worker image: %w", err)
	}
	return image, state, nil
}

func (c *workerController) Act(ctx context.Context, action Action) (ActionResult, error) {
	if err := Validate(action); err != nil {
		return ActionResult{}, err
	}
	if _, err := c.call(ctx, "act", action, &struct{}{}); err != nil {
		return ActionResult{}, err
	}
	return ActionResult{Kind: action.Kind, TargetID: action.TargetID, Success: true}, nil
}

func (c *workerController) call(ctx context.Context, method string, params, output any) (workerResponse, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	operationContext, cancel := context.WithTimeout(ctx, computerCallTimeout)
	defer cancel()
	if err := operationContext.Err(); err != nil {
		return workerResponse{}, err
	}
	if c.cmd == nil {
		if err := c.startLocked(operationContext); err != nil {
			return workerResponse{}, err
		}
	}
	c.sequence++
	request := workerRequest{ID: c.sequence, Method: method, Params: params}
	response, err := c.exchangeWithContextLocked(operationContext, request)
	if err != nil {
		return workerResponse{}, err
	}
	if response.Error != "" {
		return response, errors.New(response.Error)
	}
	if output != nil && len(response.Result) > 0 {
		if err := json.Unmarshal(response.Result, output); err != nil {
			return response, fmt.Errorf("decode Rust computer worker result: %w", err)
		}
	}
	return response, nil
}

func (c *workerController) exchangeLocked(request workerRequest) (workerResponse, error) {
	data, err := json.Marshal(request)
	if err != nil {
		return workerResponse{}, err
	}
	if len(data) > 16<<20 {
		return workerResponse{}, errors.New("computer worker request exceeds 16 MiB")
	}
	var header [4]byte
	binary.LittleEndian.PutUint32(header[:], uint32(len(data)))
	if _, err := c.stdin.Write(append(header[:], data...)); err != nil {
		c.stopLocked()
		return workerResponse{}, fmt.Errorf("write Rust computer worker: %w", err)
	}
	if _, err := io.ReadFull(c.stdout, header[:]); err != nil {
		c.stopLocked()
		return workerResponse{}, fmt.Errorf("read Rust computer worker header: %w", err)
	}
	length := binary.LittleEndian.Uint32(header[:])
	if length == 0 || length > 96<<20 {
		c.stopLocked()
		return workerResponse{}, errors.New("Rust computer worker returned an invalid frame length")
	}
	payload := make([]byte, length)
	if _, err := io.ReadFull(c.stdout, payload); err != nil {
		c.stopLocked()
		return workerResponse{}, fmt.Errorf("read Rust computer worker response: %w", err)
	}
	var response workerResponse
	if err := json.Unmarshal(payload, &response); err != nil {
		return workerResponse{}, fmt.Errorf("decode Rust computer worker response: %w", err)
	}
	if response.ID != request.ID {
		return workerResponse{}, errors.New("Rust computer worker response ID mismatch")
	}
	return response, nil
}

func (c *workerController) exchangeWithContextLocked(ctx context.Context, request workerRequest) (workerResponse, error) {
	completed := make(chan workerExchange, 1)
	go func() {
		response, err := c.exchangeLocked(request)
		completed <- workerExchange{response: response, err: err}
	}()
	select {
	case result := <-completed:
		if result.err != nil {
			c.stopLocked()
		}
		return result.response, result.err
	case <-ctx.Done():
		c.stopLocked()
		<-completed
		return workerResponse{}, fmt.Errorf("Rust computer worker operation stopped: %w", ctx.Err())
	}
}

func (c *workerController) startLocked(ctx context.Context) error {
	directory, err := os.MkdirTemp("", "lrmcp-computer-v6-")
	if err != nil {
		return fmt.Errorf("create Rust computer worker directory: %w", err)
	}
	data, err := workerExecutable.ReadFile("worker_windows_amd64.exe")
	if err != nil {
		_ = os.RemoveAll(directory)
		return err
	}
	path := filepath.Join(directory, "lrmcp-computer-worker.exe")
	if err := os.WriteFile(path, data, 0o700); err != nil {
		_ = os.RemoveAll(directory)
		return fmt.Errorf("extract Rust computer worker: %w", err)
	}
	command := exec.CommandContext(c.ctx, path)
	command.SysProcAttr = &syscall.SysProcAttr{HideWindow: true, CreationFlags: windows.CREATE_NO_WINDOW}
	stdin, err := command.StdinPipe()
	if err != nil {
		_ = os.RemoveAll(directory)
		return err
	}
	stdout, err := command.StdoutPipe()
	if err != nil {
		_ = os.RemoveAll(directory)
		return err
	}
	if err := command.Start(); err != nil {
		_ = os.RemoveAll(directory)
		return fmt.Errorf("start Rust computer worker: %w", err)
	}
	done := make(chan struct{})
	c.cmd, c.stdin, c.stdout, c.temporaryDirectory, c.done = command, stdin, bufio.NewReaderSize(stdout, 64*1024), directory, done
	go func() { _ = command.Wait(); close(done) }()
	response, err := c.exchangeWithContextLocked(ctx, workerRequest{ID: 0, Method: "hello"})
	if err != nil {
		return err
	}
	if response.Error != "" {
		c.stopLocked()
		return errors.New(response.Error)
	}
	var hello struct {
		Version string `json:"version"`
		Backend string `json:"backend"`
	}
	if err := json.Unmarshal(response.Result, &hello); err != nil {
		c.stopLocked()
		return fmt.Errorf("decode Rust computer worker handshake: %w", err)
	}
	if hello.Version != computerWorkerVersion || hello.Backend != "windows-rust-wgc-uia" {
		c.stopLocked()
		return fmt.Errorf("Rust computer worker identity mismatch: version=%q backend=%q", hello.Version, hello.Backend)
	}
	return nil
}

func (c *workerController) stopLocked() {
	if c.stdin != nil {
		_ = c.stdin.Close()
	}
	if c.cmd != nil && c.cmd.Process != nil {
		_ = c.cmd.Process.Kill()
	}
	if c.done != nil {
		select {
		case <-c.done:
		case <-time.After(2 * time.Second):
		}
	}
	if c.temporaryDirectory != "" {
		_ = os.RemoveAll(c.temporaryDirectory)
	}
	c.cmd, c.stdin, c.stdout, c.temporaryDirectory, c.done = nil, nil, nil, "", nil
}
